name: Link checking lychee
on:
  push:
    branches:
      - main

jobs:
  ci-health:
    name: "CI/Healthcare"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker # https://github.com/marketplace/actions/lychee-broken-link-checker
        uses: lycheeverse/lychee-action@v1.7.0
        with:
          fail: true
          args: --verbose --no-progress --exclude-all-private --exclude 'stackoverflow.com' --exclude 'https://api.sensible.so/v0/extract/senseml_basics' --exclude 'https://platform.openai.com' --exclude 'support.discord.com' --exclude-path 'examples' --exclude-path 'docs/snippets/callouts.mdx' .
