name: Link checking CLI
on:
  push:
    branches:
      - main
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: update linux packages
        run: sudo apt update
      - name: ensure latest node
        run: npm install -gn
      - name: install latest node
        run: n latest
      - name: check links ğŸ—
        run: bash ./scripts/check_links_cli.sh

