name: Link checking CLI
on:
  push:
    branches:
      - main
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: update linux packages
        run: sudo apt update
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 'node' # or use 'lts/*' for the latest LTS version
      - name: Check Mintfliy version
        run: npx mintlify --version
      - name: Check Mintfliy help
        run: npx mintlify --help        
      #- name: check links ğŸ—
        #run: bash ./scripts/check_links_cli.sh

